//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_data
    {
        public int Employee_Id { get; set; }
        public string Employee_name { get; set; }
        public string Email_address { get; set; }
        public string Mobile_number { get; set; }
        public string Employee_code { get; set; }
        public string Pass { get; set; }
        public string Designation { get; set; }
        public Nullable<int> Salary { get; set; }
    }
}
